config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
#   devise_for :users,skip: [:passwords], controllers: {
#   registrations: "users/registrations",
#   sessions: 'users/sessions'
# }

  get "search" => "searches#search"

  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  resources :books
  scope :book do
    post "/:id/favorites" => "favorites#create", as: 'favorites'
    delete "/favorite/:id" => "favorites#destroy", as: 'favorite'
    post "/:id/comments" => "book_comments#create", as: 'comments'
    delete "/comment/:id" => "book_comments#destroy", as: 'comment'
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # has_many :xxx, class_name: "モデル名", foreign_key: "○○_id", dependent: :destroy
  #has_many :yyy, through: :xxx, source: :zzz
  #validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  #validates :introduction, length: {maximum: 50 }
   def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :after_sign_out_path_for
  def new
  end

  def index
    @users= User.all
    @user= current_user
    @book= Book.new
  end


  def show
    #binding.pry
    @user= User.find(params[:id])
    @book= Book.new
    @books= @user.books
  end

  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render :edit
    else
    redirect_to user_path(current_user)
    end
  end

  def update
     @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="user was successfully created."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

private


  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<%= render 'users/info', user: @user,book: @book%>
</div>
<div class='col-md-8 offset-md-1' >

<h2>User</h2>
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

<% @users.each do |user| %>
  <tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>

  <td>name <%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
<% end %>

</tbody>
</table>
</div>

app/views/users/_info.html.erb
 <% if flash[:notice] %>
   <div class="alert">
    <%= flash[:notice] %>
   </div>
  <% end %>
  <h3>User</h3>
  <table class='table'>
  <tr><%#= image_tag user.get_profile_image(100,100) %>
    <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <!--<tr>-->
	 <!-- <th>introduction</th>-->
	  <th><%#= user.introduction %></th>
  <!--</tr>-->
</table>

<div>
<%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do%>
  <i class="fas fa-user-cog"></i>
 <%end%>
 </div>

 <h2 class="mt-3"><h3>★New book</h1>
<div id="error-explanation"></div>
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: book, method: :post do |f| %>
  <div class="form-group"><%= f.label :タイトル %>
  <%= f.text_field :title, class: "form-control"%></div>

  <div class="form-group"><%= f.label :説明 %>
  <%= f.text_area :body, class: "form-control"%></div>

  <div class="form-group"><%= f.submit 'Create Book', class: "btn btn-success"%>
  </div>
<% end %>

app/views/users/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= image_tag post_image.get_image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= image_tag post_image.user.get_profile_image(100,100), class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/users/edit.html.erb
<div id="error-explanation"></div>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<h1>User info</h1>


<%= form_with model: @user do |f| %>
  <%= f.label :Name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :image %>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
  <br>
  <%#= f.label :introduction %><br>
  <%#= f.text_area :introduction %><br>
  <br>
   <%= f.submit 'Update User', class: "btn btn-secondary" %>
  <br>
 <% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<%#= render 'users/info', user: @user,book: @book%>
</div>
<div class='col-md-8 offset-md-1' >

<h2>user</h2>
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>ユーザー名</th>
      <th>BOOK</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

<% @users.each do |user| %>
  <tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>

  <td> <%= user.name %></td>
  <td><%= link_to "見る", user_path(user.id), class: 'btn btn-outline-dark' %></td>
  </tr>
<% end %>

</tbody>
</table>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>

<%#= render 'info', user: @user, book: @book %>
 <%= render 'info', user: @user,book: @book %>
  </div>
<div class='col-md-8 offset-md-1' >




 <% @books.each do |book| %>
  <tr>
  <td><%#= image_tag book.user.get_profile_image(100,100) %>
  <%# binding.pry %>
  <%= link_to user_path (book.user_id) do %>
   <%= book.user.name %>
  <%end%>
  </td>
 </td>
  <td> <%#= book.user.name %></td>

  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
  </tr>

  <% end %>

  </div>
 </div>
</div>