config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
#   devise_for :users,skip: [:passwords], controllers: {
#   registrations: "users/registrations",
#   sessions: 'users/sessions'
# }

  get "search" => "searches#search"

  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  resources :books
  scope :book do
    post "/:id/favorites" => "favorites#create", as: 'favorites'
    delete "/favorite/:id" => "favorites#destroy", as: 'favorite'
    post "/:id/comments" => "book_comments#create", as: 'comments'
    delete "/comment/:id" => "book_comments#destroy", as: 'comment'
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

def favorited?(user)
   favorites.where(user_id: user.id).exists?
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user=current_user
      render :index

    end
  end

  def show
    @book=Book.find(params[:id])
    @user=@book.user
    @book_new=Book.new
    @book_comment=BookComment.new
  end
  def index
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice]="You have updated book successfully."
    redirect_to book_path(@book)
  else
    render :edit
  end
  end
  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def correct_user
    @book=Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if flash[:notice] %>
   <div class="alert">
    <%= flash[:notice] %>
   </div>
  <% end %>
  <h2>User info</h2>
  <table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %>
    <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div>
<%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do%>
  <i class="fas fa-user-cog"></i>
 <%end%>
 </div>

 <h2 class="mt-3">New book</h2>

<div id="error-explanation"></div>
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: book, method: :post do |f| %>
  <div class="form-group"><%= f.label :Title %>
  <%= f.text_field :title, class: "form-control"%></div>

  <div class="form-group"><%= f.label :Opinion %>
  <%= f.text_area :body, class: "form-control"%></div>

  <div class="form-group"><%= f.submit 'Create Book', class: "btn btn-success"%>
  </div><% end %>

app/views/books/_index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<%= render 'users/info', user: @user, book: @book %>
</div>
<div class='col-md-8 offset-md-1' >

<h2>Books</h2>
  <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
<% @books.each do | book | %>
<tr>
  <td>
    <%= link_to user_path(book.user) do%>
    <%= image_tag book.user.get_profile_image(100,100) %>
  <% end %>
  </td>

  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
  </tr>

<% end %>
</tbody>
</table>

app/views/books/edit.html.erb
<div id="error-explanation"></div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<h1>Editing Book</h1>
  

<%= form_with model: @book do |f| %>
  <%= f.label :Title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :Opinion %><br>
  <%= f.text_area :body %><br>
  <br>
   <%= f.submit 'Update Book' %>
  <br>
 <% end %>
  <br>
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
 <%= render 'users/info', user: @user, book: @book %>
 <%= render 'layouts/search', user: @user, book: @book %>
  </div>
  <div class='col-md-8 offset-md-1' >

    <h2>Books</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do | book | %>
          <tr>
            <td>
            <%= link_to user_path(book.user) do%>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </td>

            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited?(current_user) %>
                <%= button_to favorite_path(book.id), method: :delete do %>
                <span style="color:red;">❤︎</span>
                <% end %>
              <% else %>
                <%= button_to favorites_path(book.id), method: :post do %>
                <span>❤︎</span>
                <% end %>
              <% end %><%= book.favorites.count %>
            </td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>


      </tbody>
    </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<% str = "\n" %>
<% def html_safe_newline(str) h(str).gsub(/\n|\r|\r\n/, "<br>").html_safe end %>
<div class='container px-5 px-sm-0'>
 <div class='row'>
  <div class='col-md-3'>
<%= render 'users/info', user: @user, book: @book_new %>
</div>
<div class='col-md-8 offset-md-1' >


<h2>Book detail</h2>
    <table class='table'>

        <tr>
          <%= link_to @book.user.name, user_path(@book.user) %></td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%=@book.body %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book) %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' } %></td>
            <td>
              <% if @book.favorited?(current_user) %>
                <%= button_to book_favorites_path(@book), method: :delete do %>
                <span style="color:red;">❤︎</span>
                <% end %>
              <% else %>
                <%= button_to favorites_path(@book), method: :post do %>
                <span>❤︎</span>
                <% end %>
              <% end %><%= @book.favorites.count %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
          </tr>
  </table>
            <%= html_safe_newline(str) %>
                <% @book.book_comments.each do |book_comment| %>
            <div>
            <%= image_tag book_comment.user.get_profile_image(100,100) %>
            <%= book_comment.user.name %>
            <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
            </div>
            <% end %>
        <% end %>
        </tr>
         <div>
        <%= form_with url: comments_path(@book), model: [@book, @book_comment] do |f| %>

          <div class="form-group">
          <%= f.text_area :comment, class: "form-control"%></div>

          <div class="form-group"><%= f.submit '送信', class: "btn btn-success"%>
          </div>
        <% end %>
      </div>
      </div>
      </div>
     </div>