config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
#   devise_for :users,skip: [:passwords], controllers: {
#   registrations: "users/registrations",
#   sessions: 'users/sessions'
# }

  get "search" => "searches#search"

  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  resources :books
  scope :book do
    post "/:id/favorites" => "favorites#create", as: 'favorites'
    delete "/favorite/:id" => "favorites#destroy", as: 'favorite'
    post "/:id/comments" => "book_comments#create", as: 'comments'
    delete "/comment/:id" => "book_comments#destroy", as: 'comment'
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

def favorited?(user)
   favorites.where(user_id: user.id).exists?
end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # has_many :xxx, class_name: "モデル名", foreign_key: "○○_id", dependent: :destroy
  #has_many :yyy, through: :xxx, source: :zzz
  #validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  #validates :introduction, length: {maximum: 50 }
   def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  # def after_sign_out_path_for(resource)
  #   root_path
  # end

  protected

  def after_sign_out_path_for(resource_or_scope)
      root_path
  end
  
  def configure_permitted_parameters
    #binding.pry
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:id])

    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
    flash[:notice]="error."
    @user=current_user
    @book_new = Book.new
    @book_comment=BookComment.new
      render template: "books/show"
    end
  end

  def destroy
    @book_book_comment = Book_comment.find_by(user_id: current_user.id, book_id: params[:book_id])
    @book_book_comment.destroy
  redirect_to books_path

  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user=current_user
      render :index

    end
  end

  def show
    @book=Book.find(params[:id])
    @user=@book.user
    @book_new=Book.new
    @book_comment=BookComment.new
  end
  def index
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
  if @book.update(book_params)
    flash[:notice]="You have updated book successfully."
    redirect_to book_path(@book)
  else
    render :edit
  end
  end
  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def correct_user
    @book=Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book_favorite = Favorite.new(user_id: current_user.id, book_id: params[:id])
    @book_favorite.save
  redirect_to books_path
  end

  def destroy
    @book_favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:id])
    @book_favorite.destroy
  redirect_to books_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end
  
  def destroy
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_action :after_sign_out_path_for
  def new
  end

  def index
    @users= User.all
    @user= current_user
    @book= Book.new
  end


  def show
    #binding.pry
    @user= User.find(params[:id])
    @book= Book.new
    @books= @user.books
  end

  def edit
    @user=User.find(params[:id])
    if @user == current_user
      render :edit
    else
    redirect_to user_path(current_user)
    end
  end

  def update
     @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="user was successfully created."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

private


  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> about
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> signup
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Josei Collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>JoseiCollection</span></a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
          <li>
           <%= link_to user_path(current_user),class:"nav-link text-light" do%>
          <i class="fas fa-house-user"></i>Home
           <%end%>
          </li>
          <li>
            <%= link_to users_path,class:"nav-link text-light" do%>
           <i class="fas fa-users"></i>Users
          <%end%>
          </li>
          <li>
            <%= link_to books_path,class:"nav-link text-light" do%>
          <i class="fas fa-book-open"></i>Books
          <%end%>
          </li>
          <li>
          <%= link_to destroy_user_session_path,method: :delete,class:"nav-link text-light" do%>
          <%#= link_to destroy_user_session_path,method: :delete %>
          <i class="fas fa-sign-out-alt"></i>Log out
          <%end%>
          </li>
        </ul>
      </div>
      <% else %>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
          <li>
           <%= link_to root_path,class:"nav-link text-light" do%>
           <i class="fas fa-home"></i>Home
           <%end%>
          </li>
          <li>
           <%= link_to about_path,class:"nav-link text-light" do%>
           <i class="fas fa-link"></i>About
           <%end%>
          </li>
          <li>
           <%= link_to new_user_registration_path,class:"nav-link text-light" do%>
           <i class="fas fa-user-plus"></i>Sign up
           <%end%>
          </li>
          <li>
            <%= link_to new_user_session_path,class:"nav-link text-light" do%>
          <i class="fas fa-sign-in-alt"></i>Log in
          <%end%>
          </li>
          <li>
    </div>
    <%end%>
    </div>
  </nav>
</header>
<% if flash[:notice] %>
   <div class="alert">
    <%= flash[:notice] %>
   </div>
<% end %>
<main>


  <%= yield %>
</main>

   <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p> collection.inc</p>
    	</div>
    </div>
  </div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>